config/routes.rb
Rails.application.routes.draw do
 scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do

    devise_for :users
     # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'orderlist#first'
    
    # get 'api/test' => 'orderlist#test'
    get 'firstpage' => 'orderlist#first'
    # get 'toptest' => 'orderlist#top_test'

    # オーダーページ
      # 各メニューページ 
    get 'order/top' => 'orderlist#top_page'
    get 'order/set_menu' => 'orderlist#set_menu'
    get 'order/alacarte_menu' => 'orderlist#alacarte'
    get 'order/noodle_menu' => 'orderlist#noodle'
    get 'order/rice_menu' => 'orderlist#rice'
    get 'order/dessert_menu' => 'orderlist#dessert'
    get 'order/drink_menu' => 'orderlist#drink'
    get 'order/recommend_menu' => 'orderlist#recommend'
    get 'order/search' => 'orderlist#search'
    post 'order/cashier' => 'orderlist#call_cashier'
    post 'order/staff' => 'orderlist#call_staff'

      # 注文確認ページ
    get 'order/pre_order/:id' => 'orderlist#pre_order'
    delete 'order/pre_order/:id' => 'orderlist#delete_preorder', as: 'delete_preorder'
    post 'order/pre_order' => 'orderlist#post_order'
    get 'order/ordered/:id' => 'orderlist#ordered'


    get 'order/modal/:id' => 'orderlist#modal', as: 'order_indiv'
    post 'order/modal_order' => 'orderlist#order_create'
    
    # キッチン側のページ
      # テーブル状態一覧
    get 'kitchen/table' => 'kitchen#table_kitchen'
    
      # 通知一覧
    get 'kitchen/notification' => 'kitchen#notification'
    delete 'kitchen/notification/:id' => 'kitchen#destroy', as: 'notification_destroy'
    
      # 調理待一覧
    get 'kitchen/ordered' => 'kitchen#ordered_kitchen'
    delete 'kitchen/forcook/:id' => 'kitchen#destroy_order', as: 'forcook_destroy'
    post 'kitchen/cooked/:id' => 'kitchen#change_state', as: 'change_to_cooked'
    post 'kitchen/served/:id' => 'kitchen#change_state2', as: 'change_to_served'

      # 注文一覧
    get 'kitchen/served' => 'kitchen#served'

      # オプション追加一覧
    get 'kitchen/option_change' => 'kitchen#option_change'
    post 'kitchen/option_change' => 'kitchen#post_option'
    
    # 会計ページ
    get 'cashier/table' => 'cashier#table_cashier'
    get 'cashier/:id' => 'cashier#check_page'
    post 'cashier/paid' => 'cashier#paid'
    
    # 統計ページ
    get 'statistics/sales' => 'statistics#sales'
    get 'statistics/ranking' => 'statistics#ranking'
    delete 'statistics/delete_data' => 'statistics#delete_data', as: 'ranking_data_destroy'
    get 'statistics/csv' => 'statistics#csv'
    
    # メニュー追加
    get 'statistics/addmenu' => 'statistics#add_menu'
    post 'statistics/addmenu' => 'statistics#post_menu'
  end  
end

app/models/orderlist.rb
class Orderlist < ApplicationRecord
    belongs_to :user
end

app/controllers/orderlist_controller.rb
class OrderlistController < ApplicationController
    # ↓サインインしているかどうかの確認
    before_action :move_to_signin, :check_cart
    
    # def test
    #     render json: Orderlist.where(user_id: current_user.id)
    # end

    def first
    end

    def top_page
    end

    def set_menu
        @menus1 = Menu.where(category: 11)
        @menus2 = Menu.where(category: 12)
        @menus3 = Menu.where(category: 13)
        # binding.pry
    end

    def alacarte
        @menus1 = Menu.where(category: 21)
        @menus2 = Menu.where(category: 22)
        @menus3 = Menu.where(category: 23)
        # binding.pry
    end

    def noodle
        @menus1 = Menu.where(category: 31)
    end
    
    def rice
        @menus1 = Menu.where(category: 41)
        # @user = current_user.orderlists
        # アソシエーションができるかどうか試してみた：できた
    end
    
    def dessert
        @menus1 = Menu.where(category: 51)
        @menus2 = Menu.where(category: 52)
    end
    
    def drink
        @menus1 = Menu.where(category: 61)
        @menus2 = Menu.where(category: 62)
    end
    
    # 検索ページ
    def search
        @menus1 = Menu.where('name LIKE(?)', "%#{params[:keyword]}%").limit(20)
        @menus_en = Menu.where('name_en LIKE(?)', "%#{params[:keyword]}%").limit(20)
        @menus_zh = Menu.where('name_zh LIKE(?)', "%#{params[:keyword]}%").limit(20)
    end
    
    # おすすめ商品
    def recommend
        # レコメンドカテゴリーごと取り出す
        category_reco1 = Recommend.where(category_reco: 1)
        category_reco2 = Recommend.where(category_reco: 2)
        category_reco3 = Recommend.where(category_reco: 3)
        
        # 空の配列を用意
        @menus1 = []
        @menus2 = []
        @menus3 = []
        
        # カテゴリーごとのmenu_idから料理名等を取り出す
        category_reco1.each do |reco|
            @menus1 << Menu.find(reco[:menu_id])
        end
        category_reco2.each do |reco|
            @menus2 << Menu.find(reco[:menu_id])
        end
        category_reco3.each do |reco|
            @menus3 << Menu.find(reco[:menu_id])
        end
    end

    # モーダル部分
    def modal
        # パラムズのidにあったメニューを取り出す
        @menu = Menu.find(params[:id])
        @orderlist = Orderlist.new
        # 各オプションの中にものがあるかどうか
        # あったら変数に渡す
        if @menu.option1 then
            number = @menu.option1
            @option1 = Optiontable.find(number)
            @option_name1 = @option1.name_opt
            @option_name1_zh = @option1.name_opt_zh
            @option_name1_en = @option1.name_opt_en
        end
        if @menu.option2 then
            number = @menu.option2
            @option2 = Optiontable.find(number)
            @option_name2 = @option2.name_opt
            @option_name2_zh = @option2.name_opt_zh
            @option_name2_en = @option2.name_opt_en
        end
        if @menu.option3 then
            number = @menu.option3
            @option3 = Optiontable.find(number)
            @option_name3 = @option3.name_opt
            @option_name3_zh = @option3.name_opt_zh
            @option_name3_en = @option3.name_opt_en
        end
        
        respond_to do |format|
            format.html
            format.js
        end
    end
    # モーダル「カートへ」のcreate
    def order_create
        # binding.pry
        # メニュー価格の呼び出し
        menu = Menu.find(orderlist_params[:menu_id])
        menu_price = menu.price

        if orderlist_params[:option_id] then
        #     # オプション価格の呼び出し
            option = Optiontable.find(orderlist_params[:option_id])
            option_price = option.price_opt

            Orderlist.create(user_id: current_user.id, menu_id: orderlist_params[:menu_id], price: menu_price, number: orderlist_params[:number], state: "0")
        #     # ↓ここでオプションにメニューidを持たせたないのは
        #     # 未確定のところで、メニューidを持ってるかどうかで条件分岐させているから
        #     # （オプションidで条件分岐させてもよかったんだけど。。）
            Orderlist.create(user_id: current_user.id, option_id: orderlist_params[:option_id], price: option_price, number: orderlist_params[:number], state: "0")
        else
            Orderlist.create(user_id: current_user.id, menu_id: orderlist_params[:menu_id], price: menu_price, number: orderlist_params[:number], state: "0")
        end
        
        # createのあとは新しいビューに飛ばずに、backするように設定する
        # かつ、「カートに入れた」っていうメッセージを出す
        redirect_back(fallback_location: root_path)
        flash[:notice] = "カートに入りました！"
    end

    # 未確定注文のページ
    def pre_order
        # 現在ログインしているユーザーの状態が０のオーダーを引き出す
        preorder = Orderlist.where(user_id: params[:id]).where(state: 0)
        
        # ビューに渡す配列作成
        @preorder = []
        
        # 取り出したオーダーに対して、一つずつハッシュを作る
        # {:order_id, :number, :state, :menu_name, :option_name}　←キー
        # orderlistのテーブルにmenu_idはあるけど、
        # メニュー名のカラムがないからハッシュを作ってる
        preorder.each do |order|
            hash = {}
            hash[:order_id] = order.id
            hash[:number] = order.number
            hash[:state] = 1
            # viewに表示させるために必要↓
            if order.menu_id then
                number = order.menu_id
                menu = Menu.find(number)
                hash[:menu_name] = menu.name
                # 中国語と英語のメニューも呼び出している
                hash[:menu_name_zh] = menu.name_zh
                hash[:menu_name_en] = menu.name_en
            else
                number2 = order.option_id
                option = Optiontable.find(number2)
                # name2 = option.name_opt
                hash[:option_name] = option.name_opt
                hash[:option_name_zh] = option.name_opt_zh
                hash[:option_name_en] = option.name_opt_en
            end
            @preorder << hash
        end
        @orderlist = Orderlist.new
    end
    # 未確定の削除
    def delete_preorder
        orderlist = Orderlist.find(params[:id])
        orderlist.destroy if orderlist.user_id = current_user.id
        # サインインしてがメニューを注文した人なら、削除する
        redirect_back(fallback_location: root_path)
        flash[:notice] = "Something"
    end
    # 未確定のものを確定にする部分
    def post_order
        # paramsの配列を変数へ
        preorderlist = post_order_params[:orderlist]

        # 配列をeach文にかける
        preorderlist.each do |pre|
            # ↓オーダーのidを取り出す
            number = pre[":id"]
            # ↓文字列になっているため、数字にする
            number = number.to_i
            # ↓該当するidのオーダーレコードをだす
            orderlist = Orderlist.find(number)

            # ↓useridの確認
            if orderlist.user_id = current_user.id then
                # 個数の書き換え
                orderlist.number = pre[":number"]
                # 状態の書き換え
                orderlist.state = pre[":state"]
                orderlist.ordered_time = DateTime.current
                # binding.pry
                # 上書き保存
                orderlist.save
            end
        end
        
        # notificationテーブルに新しい注文が入ったことを知らせる
        Notification.create(table_id: current_user.id, state: 3)

        redirect_to order_top_path
        flash[:notice] = "something"

        # 自分が最初に作ったパラムズに対してのコード
        # 取り出したparamsは{"id"=>["17", "18"....], "number"=>[], "state"=>[]}
        # # paramsがidごとに配列になっているので、それぞれをパラムズから取り出す
        # id = params[:orderlist][:id]
        # number = params[:orderlist][:number]
        # state = params[:orderlist][:state]
        
        # # 入っている個数を数える
        # length = id.length
       
        # # while文で一つずつ取り出して保存する
        # i = 0
        # while i <= length-1 do 
        #     order_id = id[i]
        #     order_number = number[i]
        #     order_state = state[i]
            
        #     orderlist = Orderlist.find(order_id)

        #     if orderlist.user_id = current_user.id then
        #         orderlist.number = order_number
        #         orderlist.state = order_state
        #         orderlist.save
        #     end
        # i = i + 1

        # end
    end

    # 注文済画面
    def ordered
        # 現在ログインしているユーザーの状態が０のオーダーを引き出す
        ordered = Orderlist.where(user_id: params[:id]).where(state: 1..3).order('state ASC').order('id ASC')
        # binding.pry
        # ビューに渡す配列作成
        @ordered = []
        
        # 取り出したオーダーに対して、一つずつハッシュを作る
        # {:order_id, :number, :state, :menu_name, :option_name}
        ordered.each do |order|
            hash = {}
            hash[:number] = order.number
            hash[:price] = order.price
            if order.menu_id then
                number = order.menu_id
                menu = Menu.find(number)
                hash[:menu_name] = menu.name
                # 中国語と英語のメニューも呼び出している
                hash[:menu_name_zh] = menu.name_zh
                hash[:menu_name_en] = menu.name_en
            else
                number2 = order.option_id
                option = Optiontable.find(number2)
                hash[:option_name] = option.name_opt
                hash[:option_name_zh] = option.name_opt_zh
                hash[:option_name_en] = option.name_opt_en
            end
            
            if order.state == 1 then
                hash[:state] = "注文済"
                hash[:state_zh] = "已下单"
                hash[:state_en] = "Ordered"
            elsif order.state == 2 then
                hash[:state] = "調理中"
                hash[:state_zh] = "炒菜中"
                hash[:state_en] = "Cooking"
            else
                hash[:state] = "届済み"
                hash[:state_zh] = "已上菜"
                hash[:state_en] = "Served"
            end    
            
            @ordered << hash
        end
    end
    
    # 「会計」の呼び出し
    def call_cashier
        Notification.create(table_id: current_user.id, 	state: 1)

        redirect_back(fallback_location: root_path)
        flash[:error] = "something"
    end
    
    # スタッフの呼び出し
    def call_staff
        Notification.create(table_id: current_user.id, 	state: 2)

        redirect_back(fallback_location: root_path)
        flash[:error] = "something"
    end

private
    def check_cart
        # 現在ログインしているユーザーの状態が０のオーダーを引き出す
        @cart = Orderlist.where(user_id: current_user.id).where(state: 0)

    end
    def orderlist_params

app/helpers/orderlist_helper.rb
module OrderlistHelper
end

app/views/orderlist/alacarte.zh.html.erb
<div class="menu_background-color">
    <div class="menu_background">
        <header class="menu_header clearfix">
            <div class="menu_header_left">
                <div class="menu_button orange">
                    <a href="/zh/order/top">
                        <p>点菜首页</p>
                    </a>
                </div>
            </div>
            <div class="menu_button_right">
                <div class="menu_button orange">
                    <%= link_to order_cashier_path, :method => :post do %>
                        <p>结账</p>
                 	<%end%>
                </div>
                <div class="menu_button orange">
                    <%= link_to order_staff_path, :method => :post do %>
                        <p>呼叫</p>
                 	<%end%>
                </div>
                <div class="menu_button orange">
                    <a href="/zh/order/ordered/<%= current_user.id %>">
                        <p>已下单</p>
                    </a>
                </div>
                <div class="menu_button orange">
                    <a href="/zh/order/pre_order/<%= current_user.id %>">
                        <% if @cart.present? %>
                            <div id="red_dot"></div>
                        <% end %>
                        <img src="/cart.png" alt="cart">
                    </a>
                </div>
            </div>
        </header>
        <div class="menu_category">
            <div class="menu_button">
                <a href="/zh/order/set_menu">
                    <p>套餐</p>
                </a>
            </div>
            <div class="menu_button blue3">
                <a href="/zh/order/alacarte_menu">
                    <p>单品菜</p>
                </a>
            </div>
            <div class="menu_button">
                <a href="/zh/order/noodle_menu">
                    <p>面类</p>
                </a>
            </div>
            <div class="menu_button">
                <a href="/zh/order/rice_menu">
                    <p>米饭</p>
                </a>
            </div>
            <div class="menu_button">
                <a href="/zh/order/dessert_menu">
                    <p class="double2">甜品<br>汤类</p>
                </a>
            </div>
            <div class="menu_button">
                <a href="/zh/order/drink_menu">
                    <p>饮料</p>
                </a>
            </div>
        </div>
        <div class="line">
            <h2></h2>
        </div>
        <!--セットメニューに関わる部分-->
        <div class="menu_category2">
            <ul>
                <li id="category11" class="selected">
                    <p>主菜</p>
                </li>
                <li id="category12">
                    <p>副菜</p>
                </li>
                <li id="category13">
                    <p>小吃</p>
                </li>
            </ul>
        </div>
        <div class="menu_indiv clearfix">
            <div class="category11">
                <% @menus1.each do |menu| %>
                    <div class="menu_indiv_block" menuid=<%= menu.id %>>
                        <div class="menu_indiv_block2">
                            <!--<2%= link_to (order_indiv_url(menu.id)) do %>-->
                            <!--<2%= link_to (order_indiv_url(menu.id)), remote: true do %>-->
                                <%= image_tag "#{menu.image}" %>
                                <div class="menu_indiv_name">
                                    <%= menu.name_zh %>
                                </div>
                                
                            <!--<2%end%>-->
                        </div>
                    </div>
                <% end %>
            </div>
            <div class="category12">
                <% @menus2.each do |menu| %>
                    <div class="menu_indiv_block" menuid=<%= menu.id %>>
                        <!--<2%= link_to (order_indiv_url(menu.id)) do %>-->
                            <div class="menu_indiv_block2">
                                <%= image_tag "#{menu.image}" %>
                                <div class="menu_indiv_name">
                                    <%= menu.name_zh %>
                                </div>
                            </div>
                        <!--<2%end%>                            -->
                    </div>
                <% end %>
            </div>
            <div class="category13">
                <% @menus3.each do |menu| %>
                    <div class="menu_indiv_block" menuid=<%= menu.id %>>
                        <!--<2%= link_to (order_indiv_url(menu.id)) do %>-->
                            <div class="menu_indiv_block2">
                                <%= image_tag "#{menu.image}" %>
                                <div class="menu_indiv_name">
                                    <%= menu.name_zh %>
                                </div>
                            </div>
                        <!--<2%end%>-->
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

<% if flash[:notice].present? %>
    <div id="toasts">谢谢下单！</div>
<% end %>
<% if flash[:error].present? %>
    <div id="toasts">呼叫中<br><br>请稍等</div>
<% end %>

app/views/orderlist/pre_order.html.erb
<div class="menu_background-color">
    <div class="menu_background">
        <header class="menu_header clearfix">
            <div class="menu_header_left">
                <div class="menu_button orange">
                    <a href="/order/top">
                        <p>オーダーTOP</p>
                    </a>
                </div>
            </div>
            <div class="menu_button_right">
                <div class="menu_button orange">
                    <%= link_to order_cashier_path, :method => :post do %>
                        <p>会計</p>
                 	<%end%>
                </div>
                <div class="menu_button orange">
                    <%= link_to order_staff_path, :method => :post do %>
                        <p>呼出</p>
                 	<%end%>
                </div>
                <div class="menu_button orange">
                    <a href="/order/ordered/<%= current_user.id %>">
                        <p>注文済</p>
                    </a>
                </div>
                <div class="menu_button orange3">
                    <a href="#">
                        <img src="/cart2.png" alt="cart">
                    </a>
                </div>
            </div>
        </header>
        <div class="preorder_title">
            <p>
                未確定の注文です
            </p>
        </div>
        <div class="search_line">
            <h2></h2>
        </div>
        <div class="preorder_display">
            <%= form_for(@orderlist, url: '/order/pre_order') do |f| %>
                <div class="preorder_menu">
                    <% @preorder.each do |order| %>
                        <div class="preorder_menu_indiv">
                            <% if order[:menu_name] then %>
                                <div class="preorder_menu_name">
                                    <p><%= order[:menu_name] %></p>
                                </div>
                                <div class="preorder_menu_minus">
                                    <div class = "minus_btn">
                                    一    
                                    </div>
                                </div>
                                <div class="preorder_menu_number">
                                    <div class="preorder_menu_number2">
                                        <p><%= order[:number] %></p>
                                    </div>
                                </div>
                                <div class="preorder_menu_plus">
                                    <div class="plus_btn">
                                    ＋    
                                    </div>
                                </div>
                                <div class="preorder_delete">
                                    <div class="preorder_destroy">
                                        <div class="preorder_destroy_btn">
                                            <%= link_to '×', delete_preorder_path(order[:order_id]), method: :delete %>
                                        </div>
                                    </div>
                                </div>

                            <% else %>
                                <div class="preorder_menu_name">
                                    <p>　<%= order[:option_name] %></p>
                                </div>
                                <div class="preorder_menu_minus">
                                    <div class = "minus_btn">
                                    一    
                                    </div>
                                </div>
                                <div class="preorder_menu_number">
                                    <div class="preorder_menu_number2">
                                        <p><%= order[:number] %></p>
                                    </div>
                                </div>
                                <div class="preorder_menu_plus">
                                    <div class="plus_btn">
                                    ＋    
                                    </div>
                                </div>
                                <div class="preorder_delete">
                                    <div class="preorder_destroy">
                                        <div class="preorder_destroy_btn">
                                            <%= link_to '×', delete_preorder_path(order[:order_id]), method: :delete %>
                                        </div>
                                    </div>
                                </div>
                            <% end %>
                        </div>
                        <!--paramsに配列を渡す-->
                        <%= f.hidden_field(:id, name: "orderlist[][#{[:id]}]", value: order[:order_id]) %>
                        <%= f.hidden_field(:number, name: "orderlist[][#{[:number]}]", value: order[:number], :class => "orderlist_number_value") %>
                                                                                                            <!--このclassはjqueryでvalueを変えるためのもの-->
                        <%= f.hidden_field(:state, name: "orderlist[][#{[:state]}]", value: order[:state]) %>

                        <!--↓自分が最初に書いたコード-->
                        <!--<2%= f.hidden_field(:id, name: "orderlist[id][]", value: order[:order_id]) %>-->
                        <!--<2%= f.hidden_field(:number, name: "orderlist[number][]", value: order[:number], :class=>"orderlist_number_value") %>-->
                        <!--<2%= f.hidden_field(:state, name: "orderlist[state][]", value: order[:state]) %>-->
                        
                        <!--↓井上さんに描いてもらったコード-->
                        <!--キーがついたハッシュ-->
                        <!--<2%= f.hidden_field(:id, name: "orderlist[#{order[:order_id]}][order_id]", value: order[:order_id]) %>-->
                        <!--<2%= f.hidden_field(:number, name: "orderlist[#{order[:order_id]}][number]", value: order[:number], :class=>"orderlist_number_value") %>-->
                        <!--<2%= f.hidden_field(:state, name: "orderlist[#{order[:order_id]}][state]", value: order[:state]) %>-->
                    <% end %>
                </div>
                <div class="preorder_bt_div clearfix">
                <%= f.submit '注文する', class: 'preorder_button' %>
                </div>
            <% end %>
        </div>
    </div>    
</div>
<% if flash[:notice].present? %>
    <div id="toasts">削除しました！</div>
<% end %>
<% if flash[:error].present? %>
    <div id="toasts">ただいまお伺いします<br><br>少々お待ちくださいませ</div>
<% end %>

app/views/orderlist/set_menu.zh.html.erb
<div class="menu_background-color">
    <div class="menu_background">
        <header class="menu_header clearfix">
            <div class="menu_header_left">
                <div class="menu_button orange">
                    <a href="/zh/order/top">
                        <p>点菜首页</p>
                    </a>
                </div>
            </div>
            <div class="menu_button_right">
                <div class="menu_button orange">
                    <%= link_to order_cashier_path, :method => :post do %>
                        <p>结账</p>
                 	<%end%>
                </div>
                <div class="menu_button orange">
                    <%= link_to order_staff_path, :method => :post do %>
                        <p>呼叫</p>
                 	<%end%>
                </div>
                <div class="menu_button orange">
                    <a href="/zh/order/ordered/<%= current_user.id %>">
                        <p>已下单</p>
                    </a>
                </div>
                <div class="menu_button orange">
                    <a href="/zh/order/pre_order/<%= current_user.id %>">
                        <% if @cart.present? %>
                            <div id="red_dot"></div>
                        <% end %>
                        <img src="/cart.png" alt="cart">
                    </a>
                </div>
            </div>
        </header>
        <div class="menu_category">
            <div class="menu_button blue3">
                <a href="/zh/order/set_menu">
                    <p>套餐</p>
                </a>
            </div>
            <div class="menu_button">
                <a href="/zh/order/alacarte_menu">
                    <p>单品菜</p>
                </a>
            </div>
            <div class="menu_button">
                <a href="/zh/order/noodle_menu">
                    <p>面类</p>
                </a>
            </div>
            <div class="menu_button">
                <a href="/zh/order/rice_menu">
                    <p>米饭</p>
                </a>
            </div>
            <div class="menu_button">
                <a href="/zh/order/dessert_menu">
                    <p class="double2">甜品<br>汤类</p>
                </a>
            </div>
            <div class="menu_button">
                <a href="/zh/order/drink_menu">
                    <p>饮料</p>
                </a>
            </div>
        </div>
        <div class="line">
            <h2></h2>
        </div>
        <!--セットメニューに関わる部分-->
        <div class="menu_category2">
            <ul>
                <li id="category11" class="selected">
                    <p>人气套餐</p>
                </li>
                <li id="category12">
                    <p class="double">午餐/<br>简餐</p>
                </li>
                <li id="category13">
                    <p>特色套餐</p>
                </li>
            </ul>
        </div>
        <div class="menu_indiv clearfix">
            <div class="category11">
                <% @menus1.each do |menu| %>
                    <div class="menu_indiv_block" menuid=<%= menu.id %>>
                        <div class="menu_indiv_block2">
                            <!--<2%= link_to (order_indiv_url(menu.id)) do %>-->
                            <!--<2%= link_to (order_indiv_url(menu.id)), remote: true do %>-->
                                <%= image_tag "#{menu.image}" %>
                                <div class="menu_indiv_name">
                                    <%= menu.name_zh %>
                                </div>
                                
                            <!--<2%end%>-->
                        </div>
                    </div>
                <% end %>
            </div>
            <div class="category12">
                <% @menus2.each do |menu| %>
                    <div class="menu_indiv_block" menuid=<%= menu.id %>>
                        <!--<2%= link_to (order_indiv_url(menu.id)) do %>-->
                            <div class="menu_indiv_block2">
                                <%= image_tag "#{menu.image}" %>
                                <div class="menu_indiv_name">
                                    <%= menu.name_zh %>
                                </div>
                            </div>
                        <!--<2%end%>                            -->
                    </div>
                <% end %>
            </div>
            <div class="category13">
                <% @menus3.each do |menu| %>
                    <div class="menu_indiv_block" menuid=<%= menu.id %>>
                        <!--<2%= link_to (order_indiv_url(menu.id)) do %>-->
                            <div class="menu_indiv_block2">
                                <%= image_tag "#{menu.image}" %>
                                <div class="menu_indiv_name">
                                    <%= menu.name_zh %>
                                </div>
                            </div>
                        <!--<2%end%>-->
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

<% if flash[:notice].present? %>
    <div id="toasts">谢谢下单！</div>
<% end %>
<% if flash[:error].present? %>
    <div id="toasts">呼叫中<br><br>请稍等</div>
<% end %>