config/routes.rb
Rails.application.routes.draw do
 scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do

    devise_for :users
     # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'orderlist#first'
    
    # get 'api/test' => 'orderlist#test'
    get 'firstpage' => 'orderlist#first'
    # get 'toptest' => 'orderlist#top_test'

    # オーダーページ
      # 各メニューページ 
    get 'order/top' => 'orderlist#top_page'
    get 'order/set_menu' => 'orderlist#set_menu'
    get 'order/alacarte_menu' => 'orderlist#alacarte'
    get 'order/noodle_menu' => 'orderlist#noodle'
    get 'order/rice_menu' => 'orderlist#rice'
    get 'order/dessert_menu' => 'orderlist#dessert'
    get 'order/drink_menu' => 'orderlist#drink'
    get 'order/recommend_menu' => 'orderlist#recommend'
    get 'order/search' => 'orderlist#search'
    post 'order/cashier' => 'orderlist#call_cashier'
    post 'order/staff' => 'orderlist#call_staff'

      # 注文確認ページ
    get 'order/pre_order/:id' => 'orderlist#pre_order'
    delete 'order/pre_order/:id' => 'orderlist#delete_preorder', as: 'delete_preorder'
    post 'order/pre_order' => 'orderlist#post_order'
    get 'order/ordered/:id' => 'orderlist#ordered'


    get 'order/modal/:id' => 'orderlist#modal', as: 'order_indiv'
    post 'order/modal_order' => 'orderlist#order_create'
    
    # キッチン側のページ
      # テーブル状態一覧
    get 'kitchen/table' => 'kitchen#table_kitchen'
    
      # 通知一覧
    get 'kitchen/notification' => 'kitchen#notification'
    delete 'kitchen/notification/:id' => 'kitchen#destroy', as: 'notification_destroy'
    
      # 調理待一覧
    get 'kitchen/ordered' => 'kitchen#ordered_kitchen'
    delete 'kitchen/forcook/:id' => 'kitchen#destroy_order', as: 'forcook_destroy'
    post 'kitchen/cooked/:id' => 'kitchen#change_state', as: 'change_to_cooked'
    post 'kitchen/served/:id' => 'kitchen#change_state2', as: 'change_to_served'

      # 注文一覧
    get 'kitchen/served' => 'kitchen#served'

      # オプション追加一覧
    get 'kitchen/option_change' => 'kitchen#option_change'
    post 'kitchen/option_change' => 'kitchen#post_option'
    
    # 会計ページ
    get 'cashier/table' => 'cashier#table_cashier'
    get 'cashier/:id' => 'cashier#check_page'
    post 'cashier/paid' => 'cashier#paid'
    
    # 統計ページ
    get 'statistics/sales' => 'statistics#sales'
    get 'statistics/ranking' => 'statistics#ranking'
    delete 'statistics/delete_data' => 'statistics#delete_data', as: 'ranking_data_destroy'
    get 'statistics/csv' => 'statistics#csv'
    
    # メニュー追加
    get 'statistics/addmenu' => 'statistics#add_menu'
    post 'statistics/addmenu' => 'statistics#post_menu'
  end  
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
    # サインインしているかどうか、且つ権限を持っているか
    before_action :move_to_signin 

    before_action :set_beginning
    def set_beginning
        # 今月の月の始めの日時
        # その日付を渡すと、以下のデータ取得で月の途中からになってしまうから。
        @beginning = Date.current.beginning_of_month
    end

    def sales
        # 月の名前の表示
            @this_month = @beginning.strftime("%-m月")
            # 今月
            @last_month = @beginning.prev_month(1).strftime("%-m月")
            # 先月
            @month_before_last = @beginning.prev_month(2).strftime("%-m月")
            # 先々月
            
        # 各月の内容を表す数字を渡して、メソッドを呼び出す
        # 今月の会計データ
            @this_month_total = take_data(0)
        # 先月の会計データ
            @last_month_total = take_data(1)
        # 先月の会計データ
            @month_before_last_total = take_data(2)
    end

    def ranking
        @ranking_category = ["セット", "一品料理", "麺類", "ご飯類", "デザート", "飲み物"]

        # menu_idがあるオーダーを全部取り出す
        order_has_menu_id = Orderlist.where.not(menu_id: nil)

        # カテゴリーidが入った配列
        category_number = [[11,12,13], [21,22,23], [31], [41], [51,52], [61,62]]

        # 「menu_idがあるオーダー」と「月を呼び出す数字」と「カテゴリーを表す数字」を引数として
        # メソッドを呼び出す
        @last_month_ranking = get_ranking(order_has_menu_id, 1, category_number)
        @month_before_last_ranking = get_ranking(order_has_menu_id, 2, category_number)
        @three_months_ago_ranking = get_ranking(order_has_menu_id, 3, category_number)
        
        # csvファイルに渡すもの
        @last_month = @beginning.prev_month(1).strftime("%Y%m")
        @month_before_last = @beginning.prev_month(2).strftime("%Y%m")
        @three_months_ago = @beginning.prev_month(3).strftime("%Y%m")
    end

    def delete_data
        # menu_idがあるオーダーを全部取り出す
        order_has_menu_id = Orderlist.where.not(menu_id: nil)
        # 4ヶ月より前全部というのが、分からなかったので、
        # 去年から４ヶ月前というコードにした。
        four_months_ago = Date.current.end_of_month.prev_month(4)
        # 月末↑
        prev_year = @beginning.prev_year
        # 4月のオーダーを呼び出す
        @four_months_ago = order_has_menu_id.where(created_at: prev_year..four_months_ago)

        # ↓もしデータがあったら、削除する
        if @four_months_ago.present?
            @four_months_ago.each do |order|
                order.destroy
            end
        end

        redirect_back(fallback_location: root_path)
    end
    
    # メニュー追加画面
    def add_menu
        @menu = Menu.new
    end
    # 記入したメニューの保存
    def post_menu
        Menu.create(category: menu_params[:category], name: menu_params[:name], price: menu_params[:price], image: menu_params[:image], option1: menu_params[:option1], option2: menu_params[:option2], option3: menu_params[:option3])
        redirect_back(fallback_location: root_path)
    end

private
    # メニュー保存のストロングパラメータ
    def menu_params
        params.require(:menu).permit(:category, :name, :price, :image, :option1, :option2, :option3)
    end

    # 月のランキングを呼び出すメソッド
    def get_ranking(order_has_menu_id, prev_month_number, category_number)
        each_ranking = []
        # おのおのの月のオーダーを呼び出す
        monthly_order = order_has_menu_id.where(created_at: @beginning.prev_month(prev_month_number).all_month)

        # メニューテーブルからカテゴリー番号を取ってくる
        orders_with_category = []
        monthly_order.each do |order|
            subarry = []
            subarry << order.menu_id
            subarry << Menu.find(order.menu_id).category
            orders_with_category << subarry
        end
        
        category_number.each do |number|
            each_ranking << take_ranking_by_category(orders_with_category, number)
            # メソッドの呼び出し
            # それぞれのカテゴリ別の中のランキングを出すため
        end
        
        each_ranking
    end

    # カテゴリーランギングを呼び出すメソッド
    def take_ranking_by_category(orders_with_category, category_numbers)
        # 該当するカテゴリーのオーダーを取り出す
        orders_divided_by_category = orders_with_category.map do |category|
            category if category_numbers.any?{ |category_number| category[1] == category_number }
            # ここでオーダー番号を一つ一つ取り出してる
        end
        orders_divided_by_category = orders_divided_by_category.compact
        # nilを取り除く
        
        # その中で同じメニューをまとめて、それぞれの個数を数える
        orders_with_served_number  = orders_divided_by_category.group_by{|order| order[0]}.map do |date_indiv, array|
            # [date_indiv, array]
            [date_indiv, array.count]
        end
        
        # オーダーされた回数が多い順に並べる
        orders_sort_by_served_number = orders_with_served_number.sort_by{ | k, v | v }.reverse

        category_ranking = []
        # メニューの名前を取ってくる
        orders_sort_by_served_number.first(5).each do |order|
          name = Menu.find(order[0]).name
          category_ranking << name
        end

        category_ranking
    end

    # 毎日の会計データを呼び出すメソッド
    def take_data(month_num)
        # その月の全部の日付を取り出す
        month_date = @beginning.prev_month(month_num).all_month
        # その月の全部の会計データ
        month_all_total = Cashier.where(created_at: @beginning.prev_month(month_num).all_month)

    	# 日付が入る配列を作成して、
        # その日の日付を文字列にして配列に入れる	
    	all_dates = []
    	month_date.each do |date|
    		all_dates << date.strftime('%Y%m%d')
    	end

        #　全ての会計データを日別に分ける
        # その日別ごとにグループ化する
    	date_has_data = month_all_total.group_by { |a| a.created_at.strftime('%Y%m%d') }.map do |date_indiv, array|
            [date_indiv, array]
        end.to_h
        # 扱いやすいようにハッシュにする
    
        @toview =[]
        all_dates.each do |date|
        # 日付を一日ずつ取り出す
        	if date_has_data.has_key?(date) then
        	   # 該当する日に会計のデータがあったら、
        	   # その日の会計の合計を出す
        		subtotal = date_has_data[date]
        		total = 0
        		subtotal.each do |subtotal2|
        			total += subtotal2[:total]
                # total変数に入れる
        		end
        	else
        		total = 0
                # その日に会計データがなかったら、totalにゼロを入れる
        	end
        	@toview << [date, total]
            # その日の日付と会計の合計を配列に入れて、後ほどビューに渡す変数にいれる
        end
        return @toview
    end
    
    # サインインしているかどうかの確認
    def move_to_signin
        if user_signed_in? then
            user = User.find(current_user.id)
            authority = user.authority
            
            redirect_to firstpage_url if authority == 1 || authority == 2
            # サインインしてたら、権限のチェック
        else
            redirect_to new_user_session_url 
        end
    end
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/views/statistics/add_menu.html.erb
<div class="statistics_background-color add_menu_color">
    <div class="statistics_background">
        <header class="statistics_header clearfix">
            <div class="statistics_header_left">
                <div class="statistics_button">
                    <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                </div>
                <div class="statistics_button">
                    <%= link_to "メニューTOP", root_path, method: :get %>
                </div>
            </div>
            <div class="statistics_button_right">
                <div class="statistics_button">
                    <a href="/statistics/sales">
                        <p>売上</p>
                    </a>
                </div>
                <div class="statistics_button">
                    <a href="/statistics/ranking">
                        <p>ランキング</p>
                    </a>
                </div>
                <div class="statistics_button blue">
                    <a href="/statistics/addmenu">
                        <p>追加</p>
                    </a>
                </div>

            </div>
            
        </header>
        <div class="statistics_title">
            <p>
                メニュー追加
            </p>
        </div>
        <div class="statistics_line">
            <h2></h2>
        </div>
        <div class="add_menu_form">
            <%= form_for(@menu, url: '/statistics/addmenu') do |f| %>
                <div class="form_background">
                    <div class="add_menu_label_n_text">
                        <div class="add_menu_label">
                            <p><%= f.label :カテゴリー：%></p>
                        </div>
                        <div class="add_menu_text">
                            <%= f.select :category, [["ボリュームセット", "11"], ["ランチセット", "12"], ["ユニークセット", "13"], ["一品料理", "21"], ["おつまみ", "22"], ["点心", "23"], ["麺類", "31"], ["ご飯類", "41"], ["デザート", "51"], ["スープ", "52"], ["アルコール", "61"], ["ソフトドリンク", "62"]]%> 
                        </div>
                    </div>
                    <div class="add_menu_label_n_text">
                        <div class="add_menu_label">
                            <p><%= f.label :名前：%></p>
                        </div>
                        <div class="add_menu_text">
                            <%= f.text_field :name %> 
                        </div>
                    </div>
                    <div class="add_menu_label_n_text">
                        <div class="add_menu_label">
                            <p><%= f.label :価格：%></p>
                        </div>
                        <div class="add_menu_text">
                            <%= f.number_field :price %> 
                        </div>
                    </div>
                    <div class="add_menu_label_n_text">
                        <div class="add_menu_label">
                            <p><%= f.label :画像：%></p>
                        </div>
                        <div class="add_menu_text">
                            <%= f.text_field :image %> 
                        </div>
                    </div>
                    <div class="add_menu_label_n_text">
                        <div class="add_menu_label">
                            <p><%= f.label :オプション1：%></p>
                        </div>
                        <div class="add_menu_text">
                            <%= f.select :option1, [["麺変更", "1"], ["ご飯大盛", "2"], ["麺大盛", "3"], ["丼大盛", "4"], ["そば大盛", "5"], ["炒飯大盛", "6"], ["小辛", "7"], ["中辛", "8"], ["大辛", "9"]], :include_blank => true %> 
                        </div>
                    </div>
                    <div class="add_menu_label_n_text">
                        <div class="add_menu_label">
                            <p><%= f.label :オプション2：%></p>
                        </div>
                        <div class="add_menu_text">
                            <%= f.select :option2, [["麺変更", "1"], ["ご飯大盛", "2"], ["麺大盛", "3"], ["丼大盛", "4"], ["そば大盛", "5"], ["炒飯大盛", "6"], ["小辛", "7"], ["中辛", "8"], ["大辛", "9"]], :include_blank => true %> 
                        </div>
                    </div>
                    <div class="add_menu_label_n_text">
                        <div class="add_menu_label">
                            <p><%= f.label :オプション1：%></p>
                        </div>
                        <div class="add_menu_text">
                            <%= f.select :option3, [["麺変更", "1"], ["ご飯大盛", "2"], ["麺大盛", "3"], ["丼大盛", "4"], ["そば大盛", "5"], ["炒飯大盛", "6"], ["小辛", "7"], ["中辛", "8"], ["大辛", "9"]], :include_blank => true %> 
                        </div>
                    </div>
                </div>
                <div class="add_menu_submit">
                    <div class="add_menu_submit_button">
                        <%= f.submit '追加' , class: 'add_submit' %>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/statistics/ranking.html.erb
<div class="statistics_background-color">
    <div class="statistics_background">
        <header class="statistics_header clearfix">
            <div class="statistics_header_left">
                <div class="statistics_button">
                    <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                </div>
                <div class="statistics_button">
                    <%= link_to "メニューTOP", root_path, method: :get %>
                </div>
            </div>
            <div class="statistics_button_right">
                <div class="statistics_button">
                    <a href="/statistics/sales">
                        <p>売上</p>
                    </a>
                </div>
                <div class="statistics_button blue">
                    <a href="/statistics/ranking">
                        <p>ランキング</p>
                    </a>
                </div>
                <div class="statistics_button">
                    <a href="/statistics/addmenu">
                        <p>追加</p>
                    </a>
                </div>
            </div>
        </header>
        <div class="statistics_ranking">
            <div class="select_month">
                <ul class="select_month_button">
                    <li id="last_month_button" class="selected">先月</li>
                    <li id="before_last_month_button">先々月</li>
                    <li id="three_months_ago_button">三ヶ月前</li>
                </ul>
            </div>
            <div class="ranking_table clearfix">
                <div class="last_month_button">
                    <% @last_month_ranking.zip(@ranking_category).each do |ranking, category| %>
                        <div class="ranking_table_indiv">
                            <div class="ranking_table_indiv2">
                                <div class="ranking_table_indiv3">
                                    <div class="table_title"><%= category %></div>
                                    <% ranking.each.with_index(1) do |menu_name, index| %>
                                        <div class="table_ranking">
                                            <div class="table_ranking_number"><%= index %></div>
                                            <div class="table_ranking_menu"><%= menu_name %></div>
                                        </div>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                    <% end %>
                </div>
                <div class="before_last_month_button">
                    <% @month_before_last_ranking.zip(@ranking_category).each do |ranking, category| %>
                        <div class="ranking_table_indiv">
                            <div class="ranking_table_indiv2">
                                <div class="ranking_table_indiv3">
                                    <div class="table_title"><%= category %></div>
                                    <% ranking.each.with_index(1) do |menu_name, index| %>
                                        <div class="table_ranking">
                                            <div class="table_ranking_number"><%= index %></div>
                                            <div class="table_ranking_menu"><%= menu_name %></div>
                                        </div>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                    <% end %>
                </div>
                <div class="three_months_ago_button">
                    <% @three_months_ago_ranking.zip(@ranking_category).each do |ranking, category| %>
                        <div class="ranking_table_indiv">
                            <div class="ranking_table_indiv2">
                                <div class="ranking_table_indiv3">
                                    <div class="table_title"><%= category %></div>
                                    <% ranking.each.with_index(1) do |menu_name, index| %>
                                        <div class="table_ranking">
                                            <div class="table_ranking_number"><%= index %></div>
                                            <div class="table_ranking_menu"><%= menu_name %></div>
                                        </div>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>
            <div class="ranking_download">
                <div class="ranking_download_button">
                    <div class="ranking_download_button_indiv">
                        <%= link_to statistics_ranking_path(format: :csv), :method => :get do %>
                            データ<br>ダウンロード
                        <% end %>
                    </div>
                    <div class="ranking_download_button_indiv">
                        <%= link_to ranking_data_destroy_path, :method => :delete do %>
                            データ削除<br>(4ヶ月前)
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/statistics/sales.html.erb
<div class="statistics_background-color">
    <div class="statistics_background">
        <header class="statistics_header clearfix">
            <div class="statistics_header_left">
                <div class="statistics_button">
                    <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                </div>
                <div class="statistics_button">
                    <%= link_to "メニューTOP", root_path, method: :get %>
                </div>
            </div>
            <div class="statistics_button_right">
                <div class="statistics_button blue">
                    <a href="/statistics/sales">
                        <p>売上</p>
                    </a>
                </div>
                <div class="statistics_button">
                    <a href="/statistics/ranking">
                        <p>ランキング</p>
                    </a>
                </div>
                <div class="statistics_button">
                    <a href="/statistics/addmenu">
                        <p>追加</p>
                    </a>
                </div>
            </div>
        </header>
        <div class="statistics_sales">
            <div class="sales_download">
                <div class="sales_download_button">
                  <%= link_to statistics_sales_path(format: :csv), :method => :get do %>
                    <p>データ<br>ダウンロード</p>
                  <% end %>
                </div>
            </div>
            <div class="sales_display">
                <div class="sales_display_monthly">
                    <div class="sales_display_monthly_indiv">
                        <div class="month_name_div">
                            <div class="month_name_letter">
                                <p><%= @month_before_last %></p>
                            </div>
                        </div>
                        <div class="daily_sales_div">
                            <div class="daily_sales_title">
                                <div class="title_day">
                                    <p>日</p>
                                </div>
                                <div class="title_sales">
                                    <p>売上</p>
                                </div>
                            </div>
                            <% @month_before_last_total.each.with_index(1) do |total, i| %>
                                <div class="daily_sales_indiv">
                                    <div class="sales_indiv_day">
                                        <p><%= i %></p>
                                    </div>
                                    <div class="sales_indiv_sales">
                                        <p><%= total[1] %></p>
                                    </div>
                                </div>
                            <% end %>
                        </div>
                    </div>    
                </div>
                <div class="sales_display_monthly">
                    <div class="sales_display_monthly_indiv">
                        <div class="month_name_div">
                            <div class="month_name_letter">
                                <p><%= @last_month %></p>
                            </div>
                        </div>
                        <div class="daily_sales_div">
                            <div class="daily_sales_title">
                                <div class="title_day">
                                    <p>日</p>
                                </div>
                                <div class="title_sales">
                                    <p>売上</p>
                                </div>
                            </div>
                            <% @last_month_total.each.with_index(1) do |total, i| %>
                                <div class="daily_sales_indiv">
                                    <div class="sales_indiv_day">
                                        <p><%= i %></p>
                                    </div>
                                    <div class="sales_indiv_sales">
                                        <p><%= total[1] %></p>
                                    </div>
                                </div>
                            <% end %>
                        </div>
                    </div>    
                </div>
                <div class="sales_display_monthly">
                    <div class="sales_display_monthly_indiv">
                        <div class="month_name_div">
                            <div class="month_name_letter">
                                <p><%= @this_month %></p>
                            </div>
                        </div>
                        <div class="daily_sales_div">
                            <div class="daily_sales_title">
                                <div class="title_day">
                                    <p>日</p>
                                </div>
                                <div class="title_sales">
                                    <p>売上</p>
                                </div>
                            </div>
                            <% @this_month_total.each.with_index(1) do |total, i| %>
                                <div class="daily_sales_indiv">
                                    <div class="sales_indiv_day">
                                        <p><%= i %></p>
                                    </div>
                                    <div class="sales_indiv_sales">
                                        <p><%= total[1] %></p>
                                    </div>
                                </div>
                            <% end %>
                        </div>
                    </div>    
                </div>
            </div>
        </div>
    </div>
</div>