config/routes.rb
Rails.application.routes.draw do
 scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do

    devise_for :users
     # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'orderlist#first'
    
    # get 'api/test' => 'orderlist#test'
    get 'firstpage' => 'orderlist#first'
    # get 'toptest' => 'orderlist#top_test'

    # オーダーページ
      # 各メニューページ 
    get 'order/top' => 'orderlist#top_page'
    get 'order/set_menu' => 'orderlist#set_menu'
    get 'order/alacarte_menu' => 'orderlist#alacarte'
    get 'order/noodle_menu' => 'orderlist#noodle'
    get 'order/rice_menu' => 'orderlist#rice'
    get 'order/dessert_menu' => 'orderlist#dessert'
    get 'order/drink_menu' => 'orderlist#drink'
    get 'order/recommend_menu' => 'orderlist#recommend'
    get 'order/search' => 'orderlist#search'
    post 'order/cashier' => 'orderlist#call_cashier'
    post 'order/staff' => 'orderlist#call_staff'

      # 注文確認ページ
    get 'order/pre_order/:id' => 'orderlist#pre_order'
    delete 'order/pre_order/:id' => 'orderlist#delete_preorder', as: 'delete_preorder'
    post 'order/pre_order' => 'orderlist#post_order'
    get 'order/ordered/:id' => 'orderlist#ordered'


    get 'order/modal/:id' => 'orderlist#modal', as: 'order_indiv'
    post 'order/modal_order' => 'orderlist#order_create'
    
    # キッチン側のページ
      # テーブル状態一覧
    get 'kitchen/table' => 'kitchen#table_kitchen'
    
      # 通知一覧
    get 'kitchen/notification' => 'kitchen#notification'
    delete 'kitchen/notification/:id' => 'kitchen#destroy', as: 'notification_destroy'
    
      # 調理待一覧
    get 'kitchen/ordered' => 'kitchen#ordered_kitchen'
    delete 'kitchen/forcook/:id' => 'kitchen#destroy_order', as: 'forcook_destroy'
    post 'kitchen/cooked/:id' => 'kitchen#change_state', as: 'change_to_cooked'
    post 'kitchen/served/:id' => 'kitchen#change_state2', as: 'change_to_served'

      # 注文一覧
    get 'kitchen/served' => 'kitchen#served'

      # オプション追加一覧
    get 'kitchen/option_change' => 'kitchen#option_change'
    post 'kitchen/option_change' => 'kitchen#post_option'
    
    # 会計ページ
    get 'cashier/table' => 'cashier#table_cashier'
    get 'cashier/:id' => 'cashier#check_page'
    post 'cashier/paid' => 'cashier#paid'
    
    # 統計ページ
    get 'statistics/sales' => 'statistics#sales'
    get 'statistics/ranking' => 'statistics#ranking'
    delete 'statistics/delete_data' => 'statistics#delete_data', as: 'ranking_data_destroy'
    get 'statistics/csv' => 'statistics#csv'
    
    # メニュー追加
    get 'statistics/addmenu' => 'statistics#add_menu'
    post 'statistics/addmenu' => 'statistics#post_menu'
  end  
end

app/controllers/kitchen_controller.rb
class KitchenController < ApplicationController
    # サインインしているかどうかのチェック
    before_action :move_to_signin 
    # 通知があるかどうかチェック
    before_action :check_notification, except: :notification
    # flashの中身を消す
    after_action :clear_flash

    # テーブルの状態を表示
    def table_kitchen
        # ↓各テーブルの状態を入れておく配列
        @color = []
        number = 1
        # テーブルの回数だけ繰り返す
        while number <= 16 do
            # テーブル番号があるか
            if Orderlist.where(user_id: number).exists?
                # 今のテーブルのオーダーを全部抜き出す
                eachtable = Orderlist.where(user_id: number)
                # 状態が１のオーダーがあったら
                if eachtable.exists?(:state => 1)
                    color = 1
                elsif eachtable.exists?(:state => 0)
                    color = 2
                elsif eachtable.exists?(:state => 2)
                    color = 2
                elsif eachtable.exists?(:state => 3)
                    color = 2
                else
                    color = 0
                end
            #テーブル番号がなかったら 
            else
                color = 0
            end
            @color << color
            number += 1
        end
    end
    
    # 調理待の注文一覧
    def ordered_kitchen
        # 全オーダーから状態が1,2のオーダーを取り出す
        # さらにusr_idごとにグループ化して、それぞれの一番最初のデータを取り出す
        groupdata = Orderlist.where(:state => [1, 2]).group(:user_id)

        # テーブル番号を入れる配列の変数
        tablenumber = []
        
        # それぞれのユーザーの一番最初のレコードをeachにかける
        # そのレコードのuser_idを取り出して、テーブル番号を入れる変数に追加する
        groupdata.each do |data|
        #   user_id = data.user_id
        #   tablenumber << user_id
        #   上の二行のコードをまとめる↓
           tablenumber << data.user_id
        end

        # キッチンにはオーダーの順番に並び変えたいので、
        # テーブル番号の配列を時間順に並び替える

        # 新しい空の配列を作る
        tablenumber2 = []
        
        tablenumber.each do |table_id|
            #それぞれのテーブルの最新のオーダーを取り出す
            order = Orderlist.where(:user_id => table_id).order("ordered_time DESC").limit(1)
            
            # そのオーダーをした時間とテーブル番号を配列にいれ
            each_table = []
            each_table << order[0].ordered_time.strftime("%H:%M")
            each_table << table_id
            # ex. ["05:49", 1]
            
            # すべてのテーブルの時間と番号をさらに一つ上の配列に入れる
            tablenumber2 << each_table
            # ex.[["05:49", 1], ["07:53", 2], ["04:50", 3], ["17:14", 9], ["17:16", 10], ["17:18", 17], ["17:20", 19]]
        end

        # オーダー時間順に並び変えて、テーブル番号を取り出す
        tablenumber3 = []
        tablenumber2.sort.each do |time|
            tablenumber3 << time[1]
        end
        # ex. => [3, 1, 2, 9, 10, 17, 19]

        # それぞれのテーブルのオーダーを入れる配列の変数を作る
        @each_table_order = []
        # それぞれのテーブルの最後のオーダー時間を入れる配列の変数を作る
        # それぞれのテーブル番号を入れる配列の変数を作る
        @time = []
        @table_id = []

        # ユーザー番号を一つ一つ取り出す
        tablenumber3.each do |table_id|
            # その番号のuser_idを取り出して、かつstate=1のオーダーを全部取り出す
            table_order = Orderlist.where(:user_id => table_id).where(state: [1, 2]).order('id ASC')
                # 取り出したオーダーにはメニューnameがないので、
                # オーダーを一つずつ取り出して、メニューの名前を入れた新たな配列を作る
                table_order2 = []
                # 時間は最新のものでいいので、配列ではなくただの変数にする
                time = ""
                table_order.each do |order|
                    hash = {}
                    
                    hash[:order_id] = order.id
                    hash[:number] = order.number
                    hash[:state] = order.state
                    time = order.ordered_time.strftime("%H:%M")
                    
                    if order.menu_id then
                        hash[:menu_id] = order.menu_id
                    else
                        hash[:menu_id] = 0
                    end

                    # viewに表示させるために必要↓
                    if order.menu_id then
                        number = order.menu_id
                        menu = Menu.find(number)
                        hash[:menu_name] = menu.name
                        hash[:menu_name_zh] = menu.name_zh
                    else
                        number2 = order.option_id
                        option = Optiontable.find(number2)
                        hash[:option_name] = option.name_opt
                        hash[:option_name_zh] = option.name_opt_zh
                    end
                    table_order2 << hash
                end
            
                # lastorder = table_order.first
                # time = lastorder.created_at.strftime("%H:%M")
                # # binding.pry

            # 名前が付いたオーダーの配列をuser-idの順番ごとビューに渡す変数の配列に入れる
            # 時間も同様に
            @each_table_order << table_order2
            @time << time
            @table_id << table_id
        end
    end
    # 調理待一覧でメニューを消す
    def destroy_order
        Orderlist.find(params[:id]).destroy
        redirect_back(fallback_location: root_path)
    end
    # 調理待一覧で状態変更：調理済
    def change_state
        orderlist = Orderlist.find(params[:id])
        # 状態の書き換え
        orderlist.state = 2
        # 上書き保存
        orderlist.save
        redirect_back(fallback_location: root_path)
    end
    # 調理待一覧で状態を変更：提供済
    def change_state2
        orderlist = Orderlist.find(params[:id])
        # 状態の書き換え
        orderlist.state = 3
        # 上書き保存
        # binding.pry
        orderlist.save
        redirect_back(fallback_location: root_path)
    end
    
    # 注文一覧
    def served
        # テーブル番号を入れる配列の変数
        tablenumber = []
        # 全オーダーから状態が1,2,3のオーダーを取り出す
        # さらにusr_idごとにグループ化して、それぞれの一番最初のデータを取り出す
        groupdata = Orderlist.where(:state => [1, 2, 3]).group(:user_id)
        # それぞれのユーザーの一番最初のレコードをeachにかける
        # それぞれのuser_idを取り出して、
        # テーブル番号を入れる配列の変数に追加する
        groupdata.each do |data|
           user_id = data.user_id
           tablenumber << user_id
        end

        # それぞれのテーブルのオーダーを入れる配列の変数を作る
        @each_table_order = []
        # それぞれのテーブル番号を入れる配列の変数を作る
        @table_id = []

        # ユーザー番号を一つ一つ取り出す
        tablenumber.each do |table_id|
            # その番号のuser_idを取り出して、かつstate=1のオーダーを全部取り出す
            # 最初は状態の順番で並べる
            # それからidで順番に並べる
            table_order = Orderlist.where(:user_id => table_id).where(state: [1, 2, 3]).order('state ASC').order('id ASC')
                # 取り出したオーダーにはメニューnameがないので、
                # オーダーを一つずつ取り出して、メニューの名前を入れた新たな配列を作る
                table_order2 = []
                table_order.each do |order|
                    hash = {}
                    
                    hash[:order_id] = order.id
                    hash[:number] = order.number

                    # viewに表示させるために必要↓
                    if order.menu_id then
                        number = order.menu_id
                        menu = Menu.find(number)
                        hash[:menu_name] = menu.name
                        hash[:menu_name_zh] = menu.name_zh
                    else
                        number2 = order.option_id
                        option = Optiontable.find(number2)
                        hash[:option_name] = option.name_opt
                        hash[:option_name_zh] = option.name_opt_zh
                    end

                    if order.state == 1 then
                        hash[:state] = "注文済"
                        hash[:state_zh] = "已下单"
                    elsif order.state == 2 then
                        hash[:state] = "調理中"
                        hash[:state_zh] = "炒菜中"
                    else
                        hash[:state] = "届済み"
                        hash[:state_zh] = "已上菜"
                    end

                    table_order2 << hash
                end
                
            # 名前が付いたオーダーの配列をuser-idの順番ごとビューに渡す変数の配列に入れる
            # 時間も同様に
            @each_table_order << table_order2
            @table_id << table_id
        end
    end

    # 通知一覧
    def notification
        @notification = Notification.all
        
        @time = []
        @notification.each do |noti|
            @time << noti.created_at.strftime("%H:%M")
        end
    end
    # 通知の削除
    def destroy
        Notification.find(params[:id]).destroy
        redirect_back(fallback_location: root_path)
    end

    # オプション追加ページ
    def option_change
        @orderlist = Orderlist.new
    end
    # オプションの保存
    def post_option
        # オプション価格の呼び出し
        option = Optiontable.find(option_params[:option_id])
        option_price = option.price_opt
        time = DateTime.current
        Orderlist.create(user_id: option_params[:user_id], option_id: option_params[:option_id], price: option_price, number: option_params[:number], state: "1", ordered_time: time)

        redirect_back(fallback_location: root_path)
    end
    

private    
    # サインインしているかどうかの確認
    def move_to_signin
        if user_signed_in? then
            user = User.find(current_user.id)
            authority = user.authority
            
            redirect_to firstpage_url if authority == 1 
            # サインインしてたら、権限のチェック
        else
            redirect_to new_user_session_url 
        end
    end

    # 通知があるかどうかの確認
    def check_notification
        # if Notification.exists?(:id => 1)
        if Notification.exists?
            flash[:alert] = "通知"
        end
    end

    def clear_flash
        flash[:alert] = nil
    end

    def option_params
        params.require(:orderlist).permit(:user_id, :option_id, :number)
    end

    
end

app/helpers/kitchen_helper.rb
module KitchenHelper
end

app/views/kitchen/notification.html.erb
<div class="kitchen_background-color">
    <div class="kitchen_background">
        <header class="kitchen_header clearfix">
            <div class="kitchen_header_left">
                <div class="kitchen_button">
                    <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                </div>
            </div>
            <div class="kitchen_button_right">
                <div class="kitchen_button">
                    <a href="/kitchen/table">
                        <p>テーブル</p>
                    </a>
                </div>
                <div class="kitchen_button">
                    <a href="/kitchen/ordered">
                        <p>調理待</p>
                    </a>
                </div>
                <div class="kitchen_button">
                    <a href="/kitchen/option_change">
                        <p>注文変更</p>
                    </a>
                </div>
                <div class="kitchen_button blue">
                    <a href="/kitchen/notification">
                        <p>通知一覧</p>
                    </a>
                </div>
            </div>
        </header>
        <div class="kitchen_title">
            <p>
                通知一覧
            </p>
        </div>
        <div class="kitchen_line">
            <h2></h2>
        </div>
        <div class="notification_display">
            <div class="notification_div">
            <div class="notification_title">
                <ul>
                    <li class="notification_title_indiv width2">テーブル</li>
                    <li class="notification_title_indiv width1">内容</li>
                    <li class="notification_title_indiv width3">時間</li>
                    <li class="notification_title_indiv width2">削除</li>
                </ul>
            </div>
            <% @notification.zip(@time).each do |notification, time| %>
            <!--<2% @notification.each do |notification| %>-->
                <div class="notification_detail">
                    <div class="notification_table">
                        <p><%= notification[:table_id] %></p> 
                    </div>
                    
                    <% if notification[:state] == 1 then %>
                        <div class="notification_state">
                            <p>呼び出し</p>
                        </div>
                    <% elsif notification[:state] == 2 %>
                        <div class="notification_state">
                            <p>会計</p>
                        </div>
                    <% else %>
                        <div class="notification_state">
                            <p>新しい注文</p>
                        </div>
                    <% end %>
                    <div class="notification_time">
                        <p><%= time %></p>
                    </div>
                    <div class="notification_delete">
                        <div class="notification_destroy">
                            <div class="destroy_btn">
                                <%= link_to '×', notification_destroy_path(notification), method: :delete %>
                            </div>
                        </div>
                    </div>
                </div>
            <% end %>
        
        </div>
        </div>
    </div>
</div>

app/views/kitchen/notification.zh.html.erb
<div class="kitchen_background-color">
    <div class="kitchen_background">
        <header class="kitchen_header clearfix">
            <div class="kitchen_header_left">
                <div class="kitchen_button">
                    <%= link_to "退出登录", destroy_user_session_path, method: :delete %>
                </div>
            </div>
            <div class="kitchen_button_right">
                <div class="kitchen_button">
                    <a href="/zh/kitchen/table">
                        <p>座位</p>
                    </a>
                </div>
                <div class="kitchen_button">
                    <a href="/zh/kitchen/ordered">
                        <p>等菜中</p>
                    </a>
                </div>
                <div class="kitchen_button">
                    <a href="/zh/kitchen/option_change">
                        <p>改菜单</p>
                    </a>
                </div>
                <div class="kitchen_button blue">
                    <a href="/zh/kitchen/notification">
                        <p>呼叫详细</p>
                    </a>
                </div>
            </div>
        </header>
        <div class="kitchen_title">
            <p>
                呼叫详细
            </p>
        </div>
        <div class="kitchen_line">
            <h2></h2>
        </div>
        <div class="notification_display">
            <div class="notification_div">
            <div class="notification_title">
                <ul>
                    <li class="notification_title_indiv width2">座位</li>
                    <li class="notification_title_indiv width1">呼叫内容</li>
                    <li class="notification_title_indiv width3">时间</li>
                    <li class="notification_title_indiv width2">删除</li>
                </ul>
            </div>
            <% @notification.zip(@time).each do |notification, time| %>
            <!--<2% @notification.each do |notification| %>-->
                <div class="notification_detail">
                    <div class="notification_table">
                        <p><%= notification[:table_id] %></p> 
                    </div>
                    
                    <% if notification[:state] == 1 then %>
                        <div class="notification_state">
                            <p>呼叫</p>
                        </div>
                    <% elsif notification[:state] == 2 %>
                        <div class="notification_state">
                            <p>结账</p>
                        </div>
                    <% else %>
                        <div class="notification_state">
                            <p>新订单</p>
                        </div>
                    <% end %>
                    <div class="notification_time">
                        <p><%= time %></p>
                    </div>
                    <div class="notification_delete">
                        <div class="notification_destroy">
                            <div class="destroy_btn">
                                <%= link_to '×', notification_destroy_path(notification), method: :delete %>
                            </div>
                        </div>
                    </div>
                </div>
            <% end %>
        
        </div>
        </div>
    </div>
</div>

app/views/kitchen/ordered_kitchen.html.erb
<div class="kitchen_background-color">
    <div class="kitchen_background">
        <header class="kitchen_header clearfix">
            <div class="kitchen_header_left">
                <div class="kitchen_button">
                    <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                </div>
            </div>
            <div class="kitchen_button_right">
                <div class="kitchen_button">
                    <a href="/kitchen/table">
                        <p>テーブル</p>
                    </a>
                </div>
                <div class="kitchen_button blue">
                    <a href="/kitchen/ordered">
                        <p>調理待</p>
                    </a>
                </div>
                <div class="kitchen_button">
                    <a href="/kitchen/option_change">
                        <p>注文変更</p>
                    </a>
                </div>
                <div class="kitchen_button">
                    <a href="/kitchen/notification">
                        <p>通知一覧</p>
                    </a>
                </div>
            </div>
        </header>
        <div class="kitchen_title">
            <p>
                調理待ち一覧
            </p>
        </div>
        <div class="kitchen_line">
            <h2></h2>
        </div>
        <!--調理待一覧-->
        <div class="forcook_div">
            <!--各テーブル-->
            <!--テーブル毎の繰り返し-->
            <% @each_table_order.zip(@time, @table_id).each do |order, time, table_id| %>
                <!--<div class="forcook_div">-->
                <!--各テーブル-->
                <!--テーブル毎の繰り返し-->
                    <div class="forcook_table">
                        <!--ボックス同士の余白を作るためのdiv-->
                        <div class="forcook_table2">
                            <div class="forcook_table_indiv">
                                <!--注文テーブル-->
                                <div class="table_info">
                                    <div class="number_n_time">
                                        <p>テーブル番号： </p>
                                        <p class="table_n"><%= table_id %></p>

                                    </div>
                                </div>
                                <!--注文時間-->
                                <div class="table_info">
                                    <div class="number_n_time">
                                        <p>注文時間： <%= time %></p>
                                    </div>
                                </div>
                                <!--注文-->
                                <div class="forcook_menu">
                                    <!--タイトル部分-->
                                    <div class="forcook_menu_title">
                                        <div class="forcook_menu_title_name">
                                            <p>料理名</p>
                                        </div>
                                        <div class="forcook_menu_title_number">
                                            <p>数量</p>
                                        </div>
                                        <div class="forcook_menu_title_state">
                                            <p>状態</p>
                                        </div>
                                    </div>
                                    <!--詳細部分-->
                                    <!--注文ごとの繰り返し-->
                                    <% order.each do |order2| %>
                                    <div class="forcook_menu_indiv">
                                        <div class="forcook_menu_indiv_name">
                                            <% if order2[:menu_name] then %>
                                                <p><%= order2[:menu_name] %></p>
                                            <% else %>
                                                <p>　<%= order2[:option_name] %></p>
                                            <% end %>
                                            <span><%= order2[:menu_id] %></span>
                                        </div>
                                        <div class="forcook_menu_indiv_number">
                                            <p><%= order2[:number] %></p>
                                        </div>
                                        <div class="forcook_menu_indiv_state">
                                            <div class="cancel">
                                                <%= link_to '×', forcook_destroy_path(order2[:order_id]), method: :delete %>
                                            </div>
                                            <div class="cooked">
                                                <%= link_to '調理済', change_to_cooked_path(order2[:order_id]), method: :post %>
                                                <span><%= order2[:state] %></span>
                                            </div>
                                            <div class="served">
                                                <%= link_to '提供済', change_to_served_path(order2[:order_id]), method: :post %>
                                            </div>
                                        </div>
                                    </div>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                    </div>
                <!--</div>-->
            <% end %>
        </div>
    </div>
</div>

app/views/kitchen/ordered_kitchen.zh.html.erb
<div class="kitchen_background-color">
    <div class="kitchen_background">
        <header class="kitchen_header clearfix">
            <div class="kitchen_header_left">
                <div class="kitchen_button">
                    <%= link_to "退出登录", destroy_user_session_path, method: :delete %>
                </div>
            </div>
            <div class="kitchen_button_right">
                <div class="kitchen_button">
                    <a href="/zh/kitchen/table">
                        <p>座位</p>
                    </a>
                </div>
                <div class="kitchen_button blue">
                    <a href="/zh/kitchen/ordered">
                        <p>等菜中</p>
                    </a>
                </div>
                <div class="kitchen_button">
                    <a href="/zh/kitchen/option_change">
                        <p>改菜单</p>
                    </a>
                </div>
                <div class="kitchen_button">
                    <a href="/zh/kitchen/notification">
                        <p>呼叫详细</p>
                    </a>
                </div>
            </div>
        </header>
        <div class="kitchen_title">
            <p>
                等菜中座位
            </p>
        </div>
        <div class="kitchen_line">
            <h2></h2>
        </div>
        <!--調理待一覧-->
        <div class="forcook_div">
            <!--各テーブル-->
            <!--テーブル毎の繰り返し-->
            <% @each_table_order.zip(@time, @table_id).each do |order, time, table_id| %>
                <!--<div class="forcook_div">-->
                <!--各テーブル-->
                <!--テーブル毎の繰り返し-->
                    <div class="forcook_table">
                        <!--ボックス同士の余白を作るためのdiv-->
                        <div class="forcook_table2">
                            <div class="forcook_table_indiv">
                                <!--注文テーブル-->
                                <div class="table_info">
                                    <div class="number_n_time">
                                        <p>座位： </p>
                                        <p class="table_n"><%= table_id %></p>

                                    </div>
                                </div>
                                <!--注文時間-->
                                <div class="table_info">
                                    <div class="number_n_time">
                                        <p>下单时间：<%= time %></p>
                                    </div>
                                </div>
                                <!--注文-->
                                <div class="forcook_menu">
                                    <!--タイトル部分-->
                                    <div class="forcook_menu_title">
                                        <div class="forcook_menu_title_name">
                                            <p>菜名</p>
                                        </div>
                                        <div class="forcook_menu_title_number">
                                            <p>数量</p>
                                        </div>
                                        <div class="forcook_menu_title_state">
                                            <p>进度</p>
                                        </div>
                                    </div>
                                    <!--詳細部分-->
                                    <!--注文ごとの繰り返し-->
                                    <% order.each do |order2| %>
                                    <div class="forcook_menu_indiv">
                                        <div class="forcook_menu_indiv_name">
                                            <% if order2[:menu_name_zh] then %>
                                                <p><%= order2[:menu_name_zh] %></p>
                                            <% else %>
                                                <p>　<%= order2[:option_name_zh] %></p>
                                            <% end %>
                                            <span><%= order2[:menu_id] %></span>
                                        </div>
                                        <div class="forcook_menu_indiv_number">
                                            <p><%= order2[:number] %></p>
                                        </div>
                                        <div class="forcook_menu_indiv_state">
                                            <div class="cancel">
                                                <%= link_to '×', forcook_destroy_path(order2[:order_id]), method: :delete %>
                                            </div>
                                            <div class="cooked">
                                                <%= link_to '已做好', change_to_cooked_path(order2[:order_id]), method: :post %>
                                                <span><%= order2[:state] %></span>
                                            </div>
                                            <div class="served">
                                                <%= link_to '已上菜', change_to_served_path(order2[:order_id]), method: :post %>
                                            </div>
                                        </div>
                                    </div>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                    </div>
                <!--</div>-->
            <% end %>
        </div>
    </div>
</div>